In [1]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
#uploading and reading the dataset
df=pd.read_csv("50_Startups.csv")
df.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [18]:
#processing one hot encoding
df=pd.get_dummies(df,drop_first=True)
df.head()

R&D Spend  Administration  Marketing Spend  Profit  State_Florida  \
0     165349          136897           471784  192261              0   
1     162597          151377           443898  191792              0   
2     153441          101145           407934  191050              1   
3     144372          118671           383199  182901              0   
4     142107           91391           366168  166187              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [19]:
#coverting boolean data type to integer
df=df.astype(int)
df.head()

R&D Spend  Administration  Marketing Spend  Profit  State_Florida  \
0     165349          136897           471784  192261              0   
1     162597          151377           443898  191792              0   
2     153441          101145           407934  191050              1   
3     144372          118671           383199  182901              0   
4     142107           91391           366168  166187              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [23]:
#creating variable for x_train and x_test
independent=df[['R&D Spend','Administration','Marketing Spend','State_Florida','State_New York']]
independent.head()

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0     165349          136897           471784              0               1
1     162597          151377           443898              0               0
2     153441          101145           407934              1               0
3     144372          118671           383199              0               1
4     142107           91391           366168              1               0

In [24]:
#creating variable for y_train and y_test
dependent=df[['Profit']]
dependent.head()

Profit
0  192261
1  191792
2  191050
3  182901
4  166187

In [28]:
#importing train_test_split for training
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [30]:
#model creation
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [32]:
#finding slope for each input
slope=regressor.coef_
slope

array([[7.90838939e-01, 3.01972395e-02, 3.10155570e-02, 4.62827681e+02,
        3.04737841e+02]])

In [33]:
#finding intercept
intercept=regressor.intercept_
intercept

array([42403.7318072])

In [34]:
#assigning to y_pred
y_pred=regressor.predict(x_test)

In [37]:
#evaluating with r2_score
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.9358680892466282

In [39]:
#saving model
import pickle 
filename='finalized_multi_linear_model.sav'
pickle.dump(regressor,open(filename,'wb'))

In [42]:
load_model=pickle.load(open('finalized_multi_linear_model.sav','rb'))
result=load_model.predict([[1234,200,123,1,0]])

C:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [44]:
#predicting the output
result

array([[43852.30910043]])